# Generated file used for preloading a child image
set(CMAKE_BUILD_TYPE "" CACHE INTERNAL "NCS child image controlled")
set(CMAKE_VERBOSE_MAKEFILE "FALSE" CACHE INTERNAL "NCS child image controlled")
set(BOARD_DIR "/home/sword/ncs/v2.7.0/zephyr/boards/nordic/thingy53" CACHE INTERNAL "NCS child image controlled")
set(ZEPHYR_TOOLCHAIN_VARIANT "zephyr" CACHE INTERNAL "NCS child image controlled")
set(NCS_TOOLCHAIN_VERSION "NONE" CACHE INTERNAL "NCS child image controlled")
set(PM_DOMAINS "CPUNET" CACHE INTERNAL "NCS child image controlled")
set(CPUNET_PM_DOMAIN_DYNAMIC_PARTITION "empty_net_core" CACHE INTERNAL "NCS child image controlled")
set(WEST_PYTHON "/home/sword/ncs/toolchains/e9dba88316/usr/local/bin/python3.9" CACHE INTERNAL "NCS child image controlled")
set(FILE_SUFFIX "" CACHE INTERNAL "NCS child image controlled")
set(BOARD "thingy53/nrf5340/cpunet" CACHE INTERNAL "NCS child image controlled")
set(DOMAIN "CPUNET" CACHE INTERNAL "NCS child image controlled")
set(EXTRA_CONF_FILE "/home/sword/ncs/v2.7.0/nrf/subsys/bootloader/image/secure_boot.conf;/home/sword/ncs/v2.7.0/nrf/subsys/partition_manager/partition_manager_enabled.conf" CACHE INTERNAL "NCS child image controlled")
