add_custom_target(mcuboot_shared_property_target)
set_property(TARGET mcuboot_shared_property_target  PROPERTY KERNEL_HEX_NAME;zephyr.hex)
set_property(TARGET mcuboot_shared_property_target  PROPERTY ZEPHYR_BINARY_DIR;/home/sword/ncs/ncs-fund-git/ncs_fund/lesson6/fund_less6_exer2/build_1/mcuboot/zephyr)
set_property(TARGET mcuboot_shared_property_target  PROPERTY KERNEL_ELF_NAME;zephyr.elf)
set_property(TARGET mcuboot_shared_property_target  PROPERTY BUILD_BYPRODUCTS;/home/sword/ncs/ncs-fund-git/ncs_fund/lesson6/fund_less6_exer2/build_1/mcuboot/zephyr/zephyr.hex;/home/sword/ncs/ncs-fund-git/ncs_fund/lesson6/fund_less6_exer2/build_1/mcuboot/zephyr/zephyr.elf)
set_property(TARGET mcuboot_shared_property_target  PROPERTY SIGNATURE_KEY_FILE;root-rsa-2048.pem)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_DEP_FILES;/home/sword/ncs/v2.7.0/bootloader/mcuboot/boot/zephyr/pm.yml)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_FILES;/home/sword/ncs/ncs-fund-git/ncs_fund/lesson6/fund_less6_exer2/build_1/mcuboot/zephyr/include/generated/pm.yml)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_DEP_FILES;/home/sword/ncs/v2.7.0/nrf/subsys/partition_manager/pm.yml.rpmsg_nrf53)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_FILES;/home/sword/ncs/ncs-fund-git/ncs_fund/lesson6/fund_less6_exer2/build_1/mcuboot/modules/nrf/subsys/partition_manager/pm.yml.rpmsg_nrf53)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_DEP_FILES;/home/sword/ncs/v2.7.0/nrf/subsys/partition_manager/pm.yml.pcd)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_FILES;/home/sword/ncs/ncs-fund-git/ncs_fund/lesson6/fund_less6_exer2/build_1/mcuboot/modules/nrf/subsys/partition_manager/pm.yml.pcd)
set_property(TARGET mcuboot_shared_property_target  PROPERTY NRF53_MULTI_IMAGE_UPDATE;y)
set_property(TARGET mcuboot_shared_property_target  PROPERTY RAM_FLASH_ADDR;0x0)
set_property(TARGET mcuboot_shared_property_target  PROPERTY RAM_FLASH_SIZE;0x40000)
set_property(TARGET mcuboot_shared_property_target  PROPERTY RAM_FLASH_LABEL;nordic_ram_flash_controller)
